package ft.sim.statistics;

/**
 * Created by sina on 19/05/2017.
 */
public enum StatisticsVariable {
  TRAIN_ENTERED_STATION,
  TRAIN_LEFT_STATION,
  TRAIN_NORMAL_BREAK,
  TRAIN_FULL_BREAK,
  TRAIN_EMERGENCY_BREAK,
  TRAIN_SPEED,
  TRAIN_MEAN_SPEED,
  TRAIN_MAX_SPEED,
  TRAIN_STOPPED,
  TRAIN_NUM_STOPPED,
  JOURNEY_DURATION,
  JOURNEY_STARTED,
  JOURNEY_FINISHED,
  MAX_ACTIVE_TRAINS,
  MIN_ACTIVE_TRAINS,
  MIN_STATION_TRAINS,
  ACTIVE_TRAINS,
  STATION_TRAINS,
  SIMULATION_STARTED,
  SIMULATION_STOPPED,
  TRAIN_CRASH,
  TRAIN_SEEING_TRAIN_AHEAD,
  TRAIN_AHEAD_BROKEN,
  TRAIN_GOT_GREEN_SIGNAL,
  TRAIN_GOT_RED_SIGNAL,
  CRITICAL_VIOLATION,
  HIGH_VIOLATION,
  GSM_GOT_NOK
}
