package ft.sim.statistics;

/**
 * Created by sina on 19/05/2017.
 */
public enum StatisticsVariable {
  TRAIN_ENTERED_STATION,
  TRAIN_LEFT_STATION,
  NORMAL_BREAKED,
  FULL_BREAKED,
  TRAIN_SPEED,
  MEAN_SPEED,
  MAX_SPEED,
  NUM_STOPPED,
  JOURNEY_DURATION,
  MAX_ACTIVE_TRAINS,
  MIN_ACTIVE_TRAINS,
  STARTED,
  STOPPED
}
